### ISSUE TITLE
是否支持Neovim?

### ISSUE THREAD

**Issue by NamelessAshone** [yianwillis/vimcdoc#14]
您好,
        请问项目是否支持在Neovim上安装?

**Comment by flameOnYou** [comment]
我也想问找这个问题 @NamelessAshone

**Comment by flameOnYou** [comment]
Plug 'yianwillis/vimcdoc' 亲测可用

**Comment by NamelessAshone** [comment]
> Plug 'yianwillis/vimcdoc' 亲测可用

Thx！
