### ISSUE TITLE
无法用plug更新

### ISSUE THREAD

**Issue by ChenWeird** [yianwillis/vimcdoc#17]
`    Plug 'yianwillis/vimcdoc'`

更新时提示abort

**Comment by yianwillis** [comment]
I tried a new fresh .vim/ config with just plug installed and added vimcdoc as a Plug. It seems working . Can you show me more error messages?

谢谢

**Comment by ChenWeird** [comment]
Delete the old plugin content, it can be install and update.

**Comment by zhmars** [comment]
> I tried a new fresh .vim/ config with just plug installed and added vimcdoc as a Plug. It seems working . Can you show me more error messages?
> 
> 谢谢

Install a older version than <https://github.com/yianwillis/vimcdoc/commit/52bca2845819a012d31492b7dbcb6ddb625c005b>, and then update to master, you willl get this error.

```conf
x vimcdoc:
    error: Your local changes to the following files would be overwritten by checkout:
    	doc/tags-cn
    Please commit your changes or stash them before you switch branches.
    Aborting
```

It seems vimcdoc handle the help tag itself, while plugin manager like vim-plug will automatically generates help tags for all plugins.

**Comment by ChenWeird** [comment]
retry plugupdate,  still get the error: aborting

**Comment by yianwillis** [comment]
I assume there must be some diff when vim-plug automatically updates help tags. 
Can you find out the diff to tags-cn?

Thanks

**Comment by yianwillis** [comment]
I reproduced the issue. So it seems we need to keep tags-cn in sync with every change to avoid this issue.

Another workaround: go to your local vimcdoc directory, possibly under ~/.vim/plugged/vimcdoc, and type on a terminal: 

$ git reset --hard

Then :PlugUpdate should work again.

**Comment by zhmars** [comment]
We should always use latest help tags if we can. 

And if this is difficult for you to keep it update, can we remove it from repo ? Let users generate it by themselves. 

For non-plugin-manager users, just need a small step to do it.

```sh
  # after git clone
  vim -u NONE -c "helptags vimcdoc/doc" -c q
```

If there are some other reasons we should keep it. Please let me know.

By the way, workaround is just a workaround, problem is still there until we solve it actually.

> English is not my native language; please excuse typing errors. And I will really appreciate that if you can point out.

**Comment by lilydjwg** [comment]
I prefer to have it in repo (although I no longer use vimcdoc) so users don't need to remember to generate themselves on every installation they have. One can use a pre-commit hook to update tags when needed automatically.

**Comment by yianwillis** [comment]
I do plan to keep tags updated on every commit in future, so it should not be a problem moving forward.

pre-commit hook is a great suggestion. thx.

I do not think it is a great idea to ask typical users to update it manually. It is way more error prone.

**Comment by zhmars** [comment]
Ok, glad to see some new progress here. 

The pre-commit hook idea is better than mine. Thanks, lilydjwg. 

And thank you for letting me know, we now have a plan for that. I really appreciate your work. It is helpful for me. Thanks sincerely, yianwillis.
