### ISSUE TITLE
大神是否可以翻译下 NeoVim 中文文档计划 

### ISSUE THREAD

**Issue by linjialiang** [yianwillis/vimcdoc#22]
> 大神是否可以翻译下 NeoVim 中文文档计划

**Comment by yianwillis** [comment]
目前还没有考虑，将来会根据两者发展的情况而定，谢谢您的建议。

**Comment by sisrfeng** [comment]
neovim, yyds!!
期待

**Comment by Freed-Wu** [comment]
IMO, browser extension of translating can work for https://neovim.io/doc/user/
