### ISSUE TITLE
在 ‘eval.txt’ ‘1.4 字典’节，原版删去 literal-Dict   #{} 部分的内容

### ISSUE THREAD

**Issue by BenSYZ** [yianwillis/vimcdoc#26]
见标题。

VIM - Vi IMproved 8.0

**Comment by BenSYZ** [comment]
原版删去1.5 节 有关blob部分

**Comment by yianwillis** [comment]
请说明一下您使用的版本？这部分是 8.2 新增的。

**Comment by BenSYZ** [comment]
哦哦哦，是这样子啊，十分抱歉！我的vim版本是8.0的，打扰了🤦

**Comment by yianwillis** [comment]
没关系，之前的版本可参照我们早先的发布， vim 8.0 对应的是 2.0.0 Release。谢谢。

**Comment by BenSYZ** [comment]
好的，谢谢啦！
