### ISSUE TITLE
建议考虑将输出的 doc/*.cnx 文档释出到 master 分支

### ISSUE THREAD

**Issue by hotoo** [yianwillis/vimcdoc#3]
- 为了便于 vundle, git 等工具直接安装，建议在 master 分支只释出 doc/*.cnx 及其他必要文件。
- develop 开发分支则存储所有的开发文件。
- gh-pages 分支可以考虑将 vimcdoc.sf.net 的首页等内容也迁移过来 ：）

**Comment by Firef0x** [comment]
@hotoo @zrong ，您好！

目前 asins 的仓库 [asins/vimcdoc](https://github.com/asins/vimcdoc) 可以满足使用 `Pathogen`、`Vundle`、`NeoBundle` 等工具安装管理的需求。所有 `.cnx` 文件内容与此仓库保持一致。详细参见 https://github.com/asins/vimcdoc/blob/master/README.md#使用方法 。

此致！ :bow:

**Comment by hotoo** [comment]
我搜了下，GitHub 上有不少 vimcdoc 的释出文档仓库，但是均没有旧版的记录。

于是我使用 vimcdoc.sf.net 释出的各个版本，做了一份 push 到了 [vimcn/vimcdoc](https://github.com/vimcn/vimcdoc) 的 release 分支，并将 release 分支设置为默认分支，这样各个 Vim 插件工具可以很方便的安装各个版本的 Vim 中文文档了。

**Comment by Firef0x** [comment]
@hotoo 感谢您的贡献。既然如此，不妨顺便创建一个拉取请求，修改 [vimcdoc/INSTALL 的 `CVS` 一节](https://github.com/yianwillis/vimcdoc/blob/master/INSTALL#L121)为 `GIT` 一节，引导 Git 用户使用 [vimcn/vimcdoc](https://github.com/vimcn/vimcdoc) 进行安装。

**Comment by 1dot75cm** [comment]
github上搜到不少马甲，能不能把那些妖孽都收编？
asins/vimcdoc 上面的插件文档是个亮点，建议在README上添加说明，作为用户安装的入口。

**Comment by hotoo** [comment]
@1dot75cm 什么马甲？

插件的中文文档，在 [vimcn](https://github.com/vimcn) 都有独立仓库，你可以有选择的进行安装。

**Comment by 1dot75cm** [comment]
噢原来有组织，马甲就是昨天搜到的一堆vimcdoc库。
对了，组织可加入么？自己没事可以本地化一些。

**Comment by hotoo** [comment]
可以的。
不过建议你先动手翻译参与进来，参与方法请参考：

https://github.com/vimcn/vimcn.github.com

**Comment by Firef0x** [comment]
@1dot75cm 在这里又看到你了，猿粪啊！在 vimcn 上面不算过时的插件文档翻译，我都给 asins/vimcdoc 发过 PR 了，推荐使用！也期待你作出贡献！ :rose:

**Comment by 1dot75cm** [comment]
ok 好的，尽我所能吧。：）
@Firef0x 嘿嘿 猿粪

**Comment by wsdjeg** [comment]
你好，目前我在给vundle做翻译工作，期待加入vimcn

**Comment by hotoo** [comment]
@wsdjeg 翻译的怎么样了？创建个 https://github.com/vimcn/vundle.cnx 仓库并邀请你了，你可以直接 push 到这个仓库。

**Comment by wsdjeg** [comment]
目前还在进行中，会尽快完成
