### ISSUE TITLE
文档同步问题请教

### ISSUE THREAD

**Issue by YuFei29** [yianwillis/vimcdoc#38]
想知道文档是怎么保持和英文文档同步的，是每次文档较大更新的时候才会去更新中文文档吗。

因为我发现，vim英文文档是经常更新的，想知道什么办法比较好可以同步跟上英文文档。

是只进行8.1， 8.2， 9.0这样的更新，然后每次更新前把新版本的英文文档和上一版本diff一下然后更新相应的中文文档吗。

因为有点想法翻译下neovim的文档，所以想了解下。谢谢～

**Comment by GalaxySnail** [comment]
其实翻译文档一般最好是用基于 gettext 的技术，比如[中文手册页项目](https://github.com/man-pages-zh/manpages-zh)在用的 [po4a](https://github.com/mquinson/po4a)，它是每条翻译绑定到一条原文字符串的，当原文修改以后旧的翻译会失效，在翻译的文档里自动用新的原文代替过时的翻译。这样只需要经常同步上游原文，就不会出现翻译过时误导读者的情况。（不过，中文手册页翻译项目并没有经常同步上游原文。）一些较大的项目的官方翻译一般也都是类似的方法，比如 python 官方文档的翻译。这种翻译最明显的一点是你经常能看到中英文混合的文档。

**Comment by YuFei29** [comment]
> 

谢谢，很有用，以前看python文档的时候就感觉很棒。

**Comment by yianwillis** [comment]
我目前采取的办法还是不定期更新，通过比较英文文档从 commit A (上次更新到的位置) 到 commit B 生成 diff，然后相应地更新中文文档。

将来会考虑更自动点的方法，但不清楚 gettext 的方法是否效果好，很多的翻译是需要根据整句的意思通盘考虑的。

**Comment by 94kai** [comment]
> 想知道文档是怎么保持和英文文档同步的，是每次文档较大更新的时候才会去更新中文文档吗。
> 
> 因为我发现，vim英文文档是经常更新的，想知道什么办法比较好可以同步跟上英文文档。
> 
> 是只进行8.1， 8.2， 9.0这样的更新，然后每次更新前把新版本的英文文档和上一版本diff一下然后更新相应的中文文档吗。
> 
> 因为有点想法翻译下neovim的文档，所以想了解下。谢谢～

neovim文档现在有进展吗 😄

**Comment by Freed-Wu** [comment]
> neovim文档现在有进展吗 😄

Same as https://github.com/yianwillis/vimcdoc/issues/22#issuecomment-2049703082
