### ISSUE TITLE
错字

### ISSUE THREAD

**Issue by guojinyu12** [yianwillis/vimcdoc#40]
usr_41.cnx第517（这里第二行）行，“不计大小写。写。”是不是多了一个字。
> 在做字符串比较时不使用 'ignorecase' 选项。加上 "?" 表示忽略大小写。因此 "==?"
> 比较两字符串是否相等，不计大小写。写。|expr-==| 有一个完整的列表。

**Comment by yianwillis** [comment]
Fixed by 8b412d8f06515c064dfcca3589bbedbf6eaac1fa.
