### ISSUE TITLE
请问我想下载Html版的中文手册需要怎么操作啊

### ISSUE THREAD

**Issue by FantasticRhythm** [yianwillis/vimcdoc#44]
就是参考手册都是PDF版的，我想能不能有HTML版的文件，让我能以浏览器本地浏览中文手册

**Comment by AllanDowney** [comment]
[Html版中文手册](https://yianwillis.github.io/vimcdoc/)

可以参考这篇文章 [用 wget 下载整个网站](https://zhuanlan.zhihu.com/p/380793959)
有人推荐这个工具 [Httrack](https://www.cnblogs.com/dunitian/p/5061954.html)

**Comment by lilydjwg** [comment]
当初我用过 httrack，不太好用，而且默认不开 keep-alive。

**Comment by FantasticRhythm** [comment]
> git checkout gh-pages
> 
> 浏览器打开 <repo-dir>/doc/help.html.

无敌，谢谢你，这个原理是什么啊，checkout又是起什么作用啊
