### ISSUE TITLE
Vim 8.0 已经发布，是否有相应的本地化计划呢？

### ISSUE THREAD

**Issue by hotoo** [yianwillis/vimcdoc#7]
Vim-jp 已经翻译到了最新版 8.0.3，中文版似乎还没有看到什么动静。

@yianwillis 如果有时间，麻烦牵头发起 Vim 8.0 中文本地化项目，应该会有众多的开发者参与进来的。

**Comment by yianwillis** [comment]
谢谢支持。Vim 8.0 中文翻译已完成。
