### ISSUE TITLE
可以使用插件安装，INSTALL没有写？

### ISSUE THREAD

**Issue by yehuohan** [yianwillis/vimcdoc#8]
可以使用Vim插件管理器直接安装，如vim-plug等，但INSTALL中并没有相应说明。

**Comment by hotoo** [comment]
- https://github.com/yianwillis/vimcdoc/pull/5
- https://github.com/vimcn/vimcdoc
- https://github.com/yianwillis/vimcdoc/issues/3#issuecomment-88456102

**Comment by yehuohan** [comment]
好的
